I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/episode1.rpy", line 1264, in script
    
  File "game/episode1.rpy", line 1264, in <module>
    
NameError: name 'moves' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/episode1.rpy", line 1264, in script
    
  File "C:\Users\hazel\Documents\RenPy\renpy-7.3.5-sdk\renpy\ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\hazel\Documents\RenPy\renpy-7.3.5-sdk\renpy\python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\hazel\Documents\RenPy\renpy-7.3.5-sdk\renpy\python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/episode1.rpy", line 1264, in <module>
    
NameError: name 'moves' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Rocktato 0.0
Fri Feb 12 13:08:11 2021
